packages:
  - "plugins/helm/frontend"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
catalog:
  "@testing-library/jest-dom": ^6.10.0
  "@testing-library/react": ^16.3.3
  "@types/node": ^26.4.0
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.5
  "@vitejs/plugin-react": ^6.1.1
  "@vitest/coverage-v8": ^4.1.11
  cross-env: ^10.1.0
  jsdom: ^29.1.1
  typescript: ^6.0.3
  vitest: ^4.1.11
minimumReleaseAgeExclude:
  - '@litelens/core@1.7.3 || 1.7.4 || 1.7.5 || 1.7.10 || 1.7.11 || 1.7.12'
  - eslint@10.9.0 || 10.9.1
  - '@litelens/design-system@1.7.3 || 1.7.4 || 1.7.5 || 1.7.8 || 1.7.11 || 1.7.12'
  - '@tanstack/query-core@5.102.3 || 5.102.7 || 5.102.8'
  - '@tanstack/react-query@5.102.3 || 5.102.7 || 5.102.8'
  - '@types/node@26.3.0 || 26.4.0'
  - '@typescript-eslint/eslint-plugin@8.68.0'
  - '@typescript-eslint/parser@8.68.0'
  - '@typescript-eslint/project-service@8.68.0'
  - '@typescript-eslint/scope-manager@8.68.0'
  - '@typescript-eslint/tsconfig-utils@8.68.0'
  - '@typescript-eslint/type-utils@8.68.0'
  - '@typescript-eslint/types@8.68.0'
  - '@typescript-eslint/typescript-estree@8.68.0'
  - '@typescript-eslint/utils@8.68.0'
  - '@typescript-eslint/visitor-keys@8.68.0'
  - typescript-eslint@8.68.0
  - lint-staged@17.4.1
  - '@testing-library/react@16.3.3'
  - '@vitejs/plugin-react@6.1.1'
  - lucide-react@1.35.0
