// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plugin.proto

// NOTE: This proto must stay byte-identical (aside from go_package) to
// internal/plugin/pb/plugin.proto in the root module. The host app and
// plugin subprocesses communicate over this wire contract independently
// of Go import paths, so keep both copies in sync until plugins/helm is
// split into its own repository, at which point this becomes canonical.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CapabilitiesResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *CapabilitiesResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type SetClusterContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContextName    string                 `protobuf:"bytes,1,opt,name=contextName,proto3" json:"contextName,omitempty"`
	KubeconfigPath string                 `protobuf:"bytes,2,opt,name=kubeconfigPath,proto3" json:"kubeconfigPath,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetClusterContextRequest) Reset() {
	*x = SetClusterContextRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClusterContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClusterContextRequest) ProtoMessage() {}

func (x *SetClusterContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClusterContextRequest.ProtoReflect.Descriptor instead.
func (*SetClusterContextRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *SetClusterContextRequest) GetContextName() string {
	if x != nil {
		return x.ContextName
	}
	return ""
}

func (x *SetClusterContextRequest) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payloadJson,proto3" json:"payloadJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   string                 `protobuf:"bytes,1,opt,name=payloadJson,proto3" json:"payloadJson,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *InvokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\tpluginapi\"\a\n" +
	"\x05Empty\"b\n" +
	"\x14CapabilitiesResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\"d\n" +
	"\x18SetClusterContextRequest\x12 \n" +
	"\vcontextName\x18\x01 \x01(\tR\vcontextName\x12&\n" +
	"\x0ekubeconfigPath\x18\x02 \x01(\tR\x0ekubeconfigPath\"I\n" +
	"\rInvokeRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12 \n" +
	"\vpayloadJson\x18\x02 \x01(\tR\vpayloadJson\"H\n" +
	"\x0eInvokeResponse\x12 \n" +
	"\vpayloadJson\x18\x01 \x01(\tR\vpayloadJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xd9\x01\n" +
	"\x06Plugin\x12D\n" +
	"\x0fGetCapabilities\x12\x10.pluginapi.Empty\x1a\x1f.pluginapi.CapabilitiesResponse\x12J\n" +
	"\x11SetClusterContext\x12#.pluginapi.SetClusterContextRequest\x1a\x10.pluginapi.Empty\x12=\n" +
	"\x06Invoke\x12\x18.pluginapi.InvokeRequest\x1a\x19.pluginapi.InvokeResponseB>Z<github.com/litelensapp/litelens-plugins/helm/internal/server/pbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: pluginapi.Empty
	(*CapabilitiesResponse)(nil),     // 1: pluginapi.CapabilitiesResponse
	(*SetClusterContextRequest)(nil), // 2: pluginapi.SetClusterContextRequest
	(*InvokeRequest)(nil),            // 3: pluginapi.InvokeRequest
	(*InvokeResponse)(nil),           // 4: pluginapi.InvokeResponse
}
var file_plugin_proto_depIdxs = []int32{
	0, // 0: pluginapi.Plugin.GetCapabilities:input_type -> pluginapi.Empty
	2, // 1: pluginapi.Plugin.SetClusterContext:input_type -> pluginapi.SetClusterContextRequest
	3, // 2: pluginapi.Plugin.Invoke:input_type -> pluginapi.InvokeRequest
	1, // 3: pluginapi.Plugin.GetCapabilities:output_type -> pluginapi.CapabilitiesResponse
	0, // 4: pluginapi.Plugin.SetClusterContext:output_type -> pluginapi.Empty
	4, // 5: pluginapi.Plugin.Invoke:output_type -> pluginapi.InvokeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
