// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/helm.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_helm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{0}
}

type HelmChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	AppVersion    string                 `protobuf:"bytes,4,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Repository    string                 `protobuf:"bytes,5,opt,name=repository,proto3" json:"repository,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmChart) Reset() {
	*x = HelmChart{}
	mi := &file_proto_helm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmChart) ProtoMessage() {}

func (x *HelmChart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmChart.ProtoReflect.Descriptor instead.
func (*HelmChart) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{1}
}

func (x *HelmChart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmChart) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HelmChart) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmChart) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *HelmChart) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *HelmChart) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type HelmChartDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	AppVersion    string                 `protobuf:"bytes,4,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Repository    string                 `protobuf:"bytes,5,opt,name=repository,proto3" json:"repository,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Home          string                 `protobuf:"bytes,7,opt,name=home,proto3" json:"home,omitempty"`
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Sources       []string               `protobuf:"bytes,9,rep,name=sources,proto3" json:"sources,omitempty"`
	Maintainers   []string               `protobuf:"bytes,10,rep,name=maintainers,proto3" json:"maintainers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmChartDetail) Reset() {
	*x = HelmChartDetail{}
	mi := &file_proto_helm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmChartDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmChartDetail) ProtoMessage() {}

func (x *HelmChartDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmChartDetail.ProtoReflect.Descriptor instead.
func (*HelmChartDetail) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{2}
}

func (x *HelmChartDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmChartDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HelmChartDetail) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmChartDetail) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *HelmChartDetail) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *HelmChartDetail) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *HelmChartDetail) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

func (x *HelmChartDetail) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *HelmChartDetail) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *HelmChartDetail) GetMaintainers() []string {
	if x != nil {
		return x.Maintainers
	}
	return nil
}

type HelmRepository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmRepository) Reset() {
	*x = HelmRepository{}
	mi := &file_proto_helm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmRepository) ProtoMessage() {}

func (x *HelmRepository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmRepository.ProtoReflect.Descriptor instead.
func (*HelmRepository) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{3}
}

func (x *HelmRepository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmRepository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type HelmRelease struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace         string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Chart             string                 `protobuf:"bytes,3,opt,name=chart,proto3" json:"chart,omitempty"`
	ChartVersion      string                 `protobuf:"bytes,4,opt,name=chartVersion,proto3" json:"chartVersion,omitempty"`
	AppVersion        string                 `protobuf:"bytes,5,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Revision          int32                  `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	Updated           string                 `protobuf:"bytes,8,opt,name=updated,proto3" json:"updated,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Repository        string                 `protobuf:"bytes,10,opt,name=repository,proto3" json:"repository,omitempty"`
	EncodedValuesYAML string                 `protobuf:"bytes,11,opt,name=encodedValuesYAML,proto3" json:"encodedValuesYAML,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HelmRelease) Reset() {
	*x = HelmRelease{}
	mi := &file_proto_helm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmRelease) ProtoMessage() {}

func (x *HelmRelease) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmRelease.ProtoReflect.Descriptor instead.
func (*HelmRelease) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{4}
}

func (x *HelmRelease) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmRelease) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HelmRelease) GetChart() string {
	if x != nil {
		return x.Chart
	}
	return ""
}

func (x *HelmRelease) GetChartVersion() string {
	if x != nil {
		return x.ChartVersion
	}
	return ""
}

func (x *HelmRelease) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *HelmRelease) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HelmRelease) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *HelmRelease) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *HelmRelease) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *HelmRelease) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *HelmRelease) GetEncodedValuesYAML() string {
	if x != nil {
		return x.EncodedValuesYAML
	}
	return ""
}

type HelmReleaseResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmReleaseResource) Reset() {
	*x = HelmReleaseResource{}
	mi := &file_proto_helm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmReleaseResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmReleaseResource) ProtoMessage() {}

func (x *HelmReleaseResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmReleaseResource.ProtoReflect.Descriptor instead.
func (*HelmReleaseResource) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{5}
}

func (x *HelmReleaseResource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HelmReleaseResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmReleaseResource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type HelmReleaseDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Chart         string                 `protobuf:"bytes,3,opt,name=chart,proto3" json:"chart,omitempty"`
	ChartVersion  string                 `protobuf:"bytes,4,opt,name=chartVersion,proto3" json:"chartVersion,omitempty"`
	AppVersion    string                 `protobuf:"bytes,5,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Revision      int32                  `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	Updated       string                 `protobuf:"bytes,8,opt,name=updated,proto3" json:"updated,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Notes         string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	ValuesYAML    string                 `protobuf:"bytes,11,opt,name=valuesYAML,proto3" json:"valuesYAML,omitempty"`
	Resources     []*HelmReleaseResource `protobuf:"bytes,12,rep,name=resources,proto3" json:"resources,omitempty"`
	Repository    string                 `protobuf:"bytes,13,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmReleaseDetail) Reset() {
	*x = HelmReleaseDetail{}
	mi := &file_proto_helm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmReleaseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmReleaseDetail) ProtoMessage() {}

func (x *HelmReleaseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmReleaseDetail.ProtoReflect.Descriptor instead.
func (*HelmReleaseDetail) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{6}
}

func (x *HelmReleaseDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelmReleaseDetail) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HelmReleaseDetail) GetChart() string {
	if x != nil {
		return x.Chart
	}
	return ""
}

func (x *HelmReleaseDetail) GetChartVersion() string {
	if x != nil {
		return x.ChartVersion
	}
	return ""
}

func (x *HelmReleaseDetail) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *HelmReleaseDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HelmReleaseDetail) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *HelmReleaseDetail) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *HelmReleaseDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *HelmReleaseDetail) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *HelmReleaseDetail) GetValuesYAML() string {
	if x != nil {
		return x.ValuesYAML
	}
	return ""
}

func (x *HelmReleaseDetail) GetResources() []*HelmReleaseResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *HelmReleaseDetail) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

type HelmReleaseRevisionHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int32                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ChartVersion  string                 `protobuf:"bytes,2,opt,name=chartVersion,proto3" json:"chartVersion,omitempty"`
	AppVersion    string                 `protobuf:"bytes,3,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelmReleaseRevisionHistory) Reset() {
	*x = HelmReleaseRevisionHistory{}
	mi := &file_proto_helm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelmReleaseRevisionHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmReleaseRevisionHistory) ProtoMessage() {}

func (x *HelmReleaseRevisionHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmReleaseRevisionHistory.ProtoReflect.Descriptor instead.
func (*HelmReleaseRevisionHistory) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{7}
}

func (x *HelmReleaseRevisionHistory) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *HelmReleaseRevisionHistory) GetChartVersion() string {
	if x != nil {
		return x.ChartVersion
	}
	return ""
}

func (x *HelmReleaseRevisionHistory) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *HelmReleaseRevisionHistory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HelmReleaseRevisionHistory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListHelmReleasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelmReleasesRequest) Reset() {
	*x = ListHelmReleasesRequest{}
	mi := &file_proto_helm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelmReleasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelmReleasesRequest) ProtoMessage() {}

func (x *ListHelmReleasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelmReleasesRequest.ProtoReflect.Descriptor instead.
func (*ListHelmReleasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{8}
}

func (x *ListHelmReleasesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListHelmReleasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Releases      []*HelmRelease         `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelmReleasesResponse) Reset() {
	*x = ListHelmReleasesResponse{}
	mi := &file_proto_helm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelmReleasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelmReleasesResponse) ProtoMessage() {}

func (x *ListHelmReleasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelmReleasesResponse.ProtoReflect.Descriptor instead.
func (*ListHelmReleasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{9}
}

func (x *ListHelmReleasesResponse) GetReleases() []*HelmRelease {
	if x != nil {
		return x.Releases
	}
	return nil
}

type ListHelmChartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Charts        []*HelmChart           `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelmChartsResponse) Reset() {
	*x = ListHelmChartsResponse{}
	mi := &file_proto_helm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelmChartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelmChartsResponse) ProtoMessage() {}

func (x *ListHelmChartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelmChartsResponse.ProtoReflect.Descriptor instead.
func (*ListHelmChartsResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{10}
}

func (x *ListHelmChartsResponse) GetCharts() []*HelmChart {
	if x != nil {
		return x.Charts
	}
	return nil
}

type ListHelmRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repositories  []*HelmRepository      `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelmRepositoriesResponse) Reset() {
	*x = ListHelmRepositoriesResponse{}
	mi := &file_proto_helm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelmRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelmRepositoriesResponse) ProtoMessage() {}

func (x *ListHelmRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelmRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListHelmRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{11}
}

func (x *ListHelmRepositoriesResponse) GetRepositories() []*HelmRepository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type ListHelmChartVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	ChartName     string                 `protobuf:"bytes,2,opt,name=chartName,proto3" json:"chartName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelmChartVersionsRequest) Reset() {
	*x = ListHelmChartVersionsRequest{}
	mi := &file_proto_helm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelmChartVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelmChartVersionsRequest) ProtoMessage() {}

func (x *ListHelmChartVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelmChartVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListHelmChartVersionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{12}
}

func (x *ListHelmChartVersionsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListHelmChartVersionsRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

type ListHelmChartVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []string               `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHelmChartVersionsResponse) Reset() {
	*x = ListHelmChartVersionsResponse{}
	mi := &file_proto_helm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHelmChartVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHelmChartVersionsResponse) ProtoMessage() {}

func (x *ListHelmChartVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHelmChartVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListHelmChartVersionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{13}
}

func (x *ListHelmChartVersionsResponse) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetHelmChartDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	ChartName     string                 `protobuf:"bytes,2,opt,name=chartName,proto3" json:"chartName,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelmChartDetailRequest) Reset() {
	*x = GetHelmChartDetailRequest{}
	mi := &file_proto_helm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelmChartDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelmChartDetailRequest) ProtoMessage() {}

func (x *GetHelmChartDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelmChartDetailRequest.ProtoReflect.Descriptor instead.
func (*GetHelmChartDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{14}
}

func (x *GetHelmChartDetailRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetHelmChartDetailRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *GetHelmChartDetailRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetArtifactHubReadmeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	ChartName     string                 `protobuf:"bytes,2,opt,name=chartName,proto3" json:"chartName,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactHubReadmeRequest) Reset() {
	*x = GetArtifactHubReadmeRequest{}
	mi := &file_proto_helm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactHubReadmeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactHubReadmeRequest) ProtoMessage() {}

func (x *GetArtifactHubReadmeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactHubReadmeRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactHubReadmeRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{15}
}

func (x *GetArtifactHubReadmeRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GetArtifactHubReadmeRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *GetArtifactHubReadmeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetArtifactHubReadmeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readme        string                 `protobuf:"bytes,1,opt,name=readme,proto3" json:"readme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactHubReadmeResponse) Reset() {
	*x = GetArtifactHubReadmeResponse{}
	mi := &file_proto_helm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactHubReadmeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactHubReadmeResponse) ProtoMessage() {}

func (x *GetArtifactHubReadmeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactHubReadmeResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactHubReadmeResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{16}
}

func (x *GetArtifactHubReadmeResponse) GetReadme() string {
	if x != nil {
		return x.Readme
	}
	return ""
}

type InstallHelmChartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName   string                 `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	ChartName     string                 `protobuf:"bytes,4,opt,name=chartName,proto3" json:"chartName,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	ValuesYAML    string                 `protobuf:"bytes,6,opt,name=valuesYAML,proto3" json:"valuesYAML,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallHelmChartRequest) Reset() {
	*x = InstallHelmChartRequest{}
	mi := &file_proto_helm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallHelmChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallHelmChartRequest) ProtoMessage() {}

func (x *InstallHelmChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallHelmChartRequest.ProtoReflect.Descriptor instead.
func (*InstallHelmChartRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{17}
}

func (x *InstallHelmChartRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InstallHelmChartRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *InstallHelmChartRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *InstallHelmChartRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *InstallHelmChartRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallHelmChartRequest) GetValuesYAML() string {
	if x != nil {
		return x.ValuesYAML
	}
	return ""
}

type UpgradeHelmReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName   string                 `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	ChartName     string                 `protobuf:"bytes,4,opt,name=chartName,proto3" json:"chartName,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	ValuesYAML    string                 `protobuf:"bytes,6,opt,name=valuesYAML,proto3" json:"valuesYAML,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeHelmReleaseRequest) Reset() {
	*x = UpgradeHelmReleaseRequest{}
	mi := &file_proto_helm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeHelmReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeHelmReleaseRequest) ProtoMessage() {}

func (x *UpgradeHelmReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeHelmReleaseRequest.ProtoReflect.Descriptor instead.
func (*UpgradeHelmReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{18}
}

func (x *UpgradeHelmReleaseRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpgradeHelmReleaseRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *UpgradeHelmReleaseRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *UpgradeHelmReleaseRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *UpgradeHelmReleaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpgradeHelmReleaseRequest) GetValuesYAML() string {
	if x != nil {
		return x.ValuesYAML
	}
	return ""
}

type DeleteHelmReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName   string                 `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHelmReleaseRequest) Reset() {
	*x = DeleteHelmReleaseRequest{}
	mi := &file_proto_helm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHelmReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHelmReleaseRequest) ProtoMessage() {}

func (x *DeleteHelmReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHelmReleaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteHelmReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteHelmReleaseRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteHelmReleaseRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

type GetHelmReleaseByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName   string                 `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelmReleaseByNameRequest) Reset() {
	*x = GetHelmReleaseByNameRequest{}
	mi := &file_proto_helm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelmReleaseByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelmReleaseByNameRequest) ProtoMessage() {}

func (x *GetHelmReleaseByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelmReleaseByNameRequest.ProtoReflect.Descriptor instead.
func (*GetHelmReleaseByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{20}
}

func (x *GetHelmReleaseByNameRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetHelmReleaseByNameRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

type GetHelmChartValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	ChartName     string                 `protobuf:"bytes,2,opt,name=chartName,proto3" json:"chartName,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelmChartValuesRequest) Reset() {
	*x = GetHelmChartValuesRequest{}
	mi := &file_proto_helm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelmChartValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelmChartValuesRequest) ProtoMessage() {}

func (x *GetHelmChartValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelmChartValuesRequest.ProtoReflect.Descriptor instead.
func (*GetHelmChartValuesRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{21}
}

func (x *GetHelmChartValuesRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetHelmChartValuesRequest) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *GetHelmChartValuesRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetHelmChartValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValuesYAML    string                 `protobuf:"bytes,1,opt,name=valuesYAML,proto3" json:"valuesYAML,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelmChartValuesResponse) Reset() {
	*x = GetHelmChartValuesResponse{}
	mi := &file_proto_helm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelmChartValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelmChartValuesResponse) ProtoMessage() {}

func (x *GetHelmChartValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelmChartValuesResponse.ProtoReflect.Descriptor instead.
func (*GetHelmChartValuesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{22}
}

func (x *GetHelmChartValuesResponse) GetValuesYAML() string {
	if x != nil {
		return x.ValuesYAML
	}
	return ""
}

type GetHelmReleaseHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName   string                 `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelmReleaseHistoryRequest) Reset() {
	*x = GetHelmReleaseHistoryRequest{}
	mi := &file_proto_helm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelmReleaseHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelmReleaseHistoryRequest) ProtoMessage() {}

func (x *GetHelmReleaseHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelmReleaseHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHelmReleaseHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{23}
}

func (x *GetHelmReleaseHistoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetHelmReleaseHistoryRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

type GetHelmReleaseHistoryResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	History       []*HelmReleaseRevisionHistory `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelmReleaseHistoryResponse) Reset() {
	*x = GetHelmReleaseHistoryResponse{}
	mi := &file_proto_helm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelmReleaseHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelmReleaseHistoryResponse) ProtoMessage() {}

func (x *GetHelmReleaseHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelmReleaseHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHelmReleaseHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{24}
}

func (x *GetHelmReleaseHistoryResponse) GetHistory() []*HelmReleaseRevisionHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type RollbackHelmReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ReleaseName   string                 `protobuf:"bytes,2,opt,name=releaseName,proto3" json:"releaseName,omitempty"`
	Revision      int32                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackHelmReleaseRequest) Reset() {
	*x = RollbackHelmReleaseRequest{}
	mi := &file_proto_helm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackHelmReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackHelmReleaseRequest) ProtoMessage() {}

func (x *RollbackHelmReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackHelmReleaseRequest.ProtoReflect.Descriptor instead.
func (*RollbackHelmReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{25}
}

func (x *RollbackHelmReleaseRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RollbackHelmReleaseRequest) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

func (x *RollbackHelmReleaseRequest) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_helm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{26}
}

func (x *CapabilitiesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CapabilitiesResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *CapabilitiesResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type SetClusterContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContextName    string                 `protobuf:"bytes,1,opt,name=contextName,proto3" json:"contextName,omitempty"`
	KubeconfigPath string                 `protobuf:"bytes,2,opt,name=kubeconfigPath,proto3" json:"kubeconfigPath,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetClusterContextRequest) Reset() {
	*x = SetClusterContextRequest{}
	mi := &file_proto_helm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClusterContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClusterContextRequest) ProtoMessage() {}

func (x *SetClusterContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClusterContextRequest.ProtoReflect.Descriptor instead.
func (*SetClusterContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_helm_proto_rawDescGZIP(), []int{27}
}

func (x *SetClusterContextRequest) GetContextName() string {
	if x != nil {
		return x.ContextName
	}
	return ""
}

func (x *SetClusterContextRequest) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

var File_proto_helm_proto protoreflect.FileDescriptor

const file_proto_helm_proto_rawDesc = "" +
	"\n" +
	"\x10proto/helm.proto\x12\x04helm\"\a\n" +
	"\x05Empty\"\xaf\x01\n" +
	"\tHelmChart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x04 \x01(\tR\n" +
	"appVersion\x12\x1e\n" +
	"\n" +
	"repository\x18\x05 \x01(\tR\n" +
	"repository\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\"\xa1\x02\n" +
	"\x0fHelmChartDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x04 \x01(\tR\n" +
	"appVersion\x12\x1e\n" +
	"\n" +
	"repository\x18\x05 \x01(\tR\n" +
	"repository\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x12\n" +
	"\x04home\x18\a \x01(\tR\x04home\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\x12\x18\n" +
	"\asources\x18\t \x03(\tR\asources\x12 \n" +
	"\vmaintainers\x18\n" +
	" \x03(\tR\vmaintainers\"6\n" +
	"\x0eHelmRepository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xd3\x02\n" +
	"\vHelmRelease\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05chart\x18\x03 \x01(\tR\x05chart\x12\"\n" +
	"\fchartVersion\x18\x04 \x01(\tR\fchartVersion\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x05 \x01(\tR\n" +
	"appVersion\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\brevision\x18\a \x01(\x05R\brevision\x12\x18\n" +
	"\aupdated\x18\b \x01(\tR\aupdated\x12\x1c\n" +
	"\tupdatedAt\x18\t \x01(\tR\tupdatedAt\x12\x1e\n" +
	"\n" +
	"repository\x18\n" +
	" \x01(\tR\n" +
	"repository\x12,\n" +
	"\x11encodedValuesYAML\x18\v \x01(\tR\x11encodedValuesYAML\"[\n" +
	"\x13HelmReleaseResource\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"\x9a\x03\n" +
	"\x11HelmReleaseDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05chart\x18\x03 \x01(\tR\x05chart\x12\"\n" +
	"\fchartVersion\x18\x04 \x01(\tR\fchartVersion\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x05 \x01(\tR\n" +
	"appVersion\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\brevision\x18\a \x01(\x05R\brevision\x12\x18\n" +
	"\aupdated\x18\b \x01(\tR\aupdated\x12\x1c\n" +
	"\tupdatedAt\x18\t \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x12\x1e\n" +
	"\n" +
	"valuesYAML\x18\v \x01(\tR\n" +
	"valuesYAML\x127\n" +
	"\tresources\x18\f \x03(\v2\x19.helm.HelmReleaseResourceR\tresources\x12\x1e\n" +
	"\n" +
	"repository\x18\r \x01(\tR\n" +
	"repository\"\xb2\x01\n" +
	"\x1aHelmReleaseRevisionHistory\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x05R\brevision\x12\"\n" +
	"\fchartVersion\x18\x02 \x01(\tR\fchartVersion\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"7\n" +
	"\x17ListHelmReleasesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"I\n" +
	"\x18ListHelmReleasesResponse\x12-\n" +
	"\breleases\x18\x01 \x03(\v2\x11.helm.HelmReleaseR\breleases\"A\n" +
	"\x16ListHelmChartsResponse\x12'\n" +
	"\x06charts\x18\x01 \x03(\v2\x0f.helm.HelmChartR\x06charts\"X\n" +
	"\x1cListHelmRepositoriesResponse\x128\n" +
	"\frepositories\x18\x01 \x03(\v2\x14.helm.HelmRepositoryR\frepositories\"\\\n" +
	"\x1cListHelmChartVersionsRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x1c\n" +
	"\tchartName\x18\x02 \x01(\tR\tchartName\";\n" +
	"\x1dListHelmChartVersionsResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\tR\bversions\"s\n" +
	"\x19GetHelmChartDetailRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x1c\n" +
	"\tchartName\x18\x02 \x01(\tR\tchartName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"i\n" +
	"\x1bGetArtifactHubReadmeRequest\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1c\n" +
	"\tchartName\x18\x02 \x01(\tR\tchartName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"6\n" +
	"\x1cGetArtifactHubReadmeResponse\x12\x16\n" +
	"\x06readme\x18\x01 \x01(\tR\x06readme\"\xd1\x01\n" +
	"\x17InstallHelmChartRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vreleaseName\x18\x02 \x01(\tR\vreleaseName\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x1c\n" +
	"\tchartName\x18\x04 \x01(\tR\tchartName\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"valuesYAML\x18\x06 \x01(\tR\n" +
	"valuesYAML\"\xd3\x01\n" +
	"\x19UpgradeHelmReleaseRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vreleaseName\x18\x02 \x01(\tR\vreleaseName\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x1c\n" +
	"\tchartName\x18\x04 \x01(\tR\tchartName\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"valuesYAML\x18\x06 \x01(\tR\n" +
	"valuesYAML\"Z\n" +
	"\x18DeleteHelmReleaseRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vreleaseName\x18\x02 \x01(\tR\vreleaseName\"]\n" +
	"\x1bGetHelmReleaseByNameRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vreleaseName\x18\x02 \x01(\tR\vreleaseName\"s\n" +
	"\x19GetHelmChartValuesRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x1c\n" +
	"\tchartName\x18\x02 \x01(\tR\tchartName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"<\n" +
	"\x1aGetHelmChartValuesResponse\x12\x1e\n" +
	"\n" +
	"valuesYAML\x18\x01 \x01(\tR\n" +
	"valuesYAML\"^\n" +
	"\x1cGetHelmReleaseHistoryRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vreleaseName\x18\x02 \x01(\tR\vreleaseName\"[\n" +
	"\x1dGetHelmReleaseHistoryResponse\x12:\n" +
	"\ahistory\x18\x01 \x03(\v2 .helm.HelmReleaseRevisionHistoryR\ahistory\"x\n" +
	"\x1aRollbackHelmReleaseRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vreleaseName\x18\x02 \x01(\tR\vreleaseName\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x05R\brevision\"b\n" +
	"\x14CapabilitiesResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\"d\n" +
	"\x18SetClusterContextRequest\x12 \n" +
	"\vcontextName\x18\x01 \x01(\tR\vcontextName\x12&\n" +
	"\x0ekubeconfigPath\x18\x02 \x01(\tR\x0ekubeconfigPath2\xd4\t\n" +
	"\x04Helm\x12;\n" +
	"\x0eListHelmCharts\x12\v.helm.Empty\x1a\x1c.helm.ListHelmChartsResponse\x12G\n" +
	"\x14ListHelmRepositories\x12\v.helm.Empty\x1a\".helm.ListHelmRepositoriesResponse\x12Q\n" +
	"\x10ListHelmReleases\x12\x1d.helm.ListHelmReleasesRequest\x1a\x1e.helm.ListHelmReleasesResponse\x12`\n" +
	"\x15ListHelmChartVersions\x12\".helm.ListHelmChartVersionsRequest\x1a#.helm.ListHelmChartVersionsResponse\x12L\n" +
	"\x12GetHelmChartDetail\x12\x1f.helm.GetHelmChartDetailRequest\x1a\x15.helm.HelmChartDetail\x12]\n" +
	"\x14GetArtifactHubReadme\x12!.helm.GetArtifactHubReadmeRequest\x1a\".helm.GetArtifactHubReadmeResponse\x12>\n" +
	"\x10InstallHelmChart\x12\x1d.helm.InstallHelmChartRequest\x1a\v.helm.Empty\x12B\n" +
	"\x12UpgradeHelmRelease\x12\x1f.helm.UpgradeHelmReleaseRequest\x1a\v.helm.Empty\x12@\n" +
	"\x11DeleteHelmRelease\x12\x1e.helm.DeleteHelmReleaseRequest\x1a\v.helm.Empty\x12K\n" +
	"\x1cDeleteHelmReleaseWithCleanup\x12\x1e.helm.DeleteHelmReleaseRequest\x1a\v.helm.Empty\x12R\n" +
	"\x14GetHelmReleaseByName\x12!.helm.GetHelmReleaseByNameRequest\x1a\x17.helm.HelmReleaseDetail\x12W\n" +
	"\x12GetHelmChartValues\x12\x1f.helm.GetHelmChartValuesRequest\x1a .helm.GetHelmChartValuesResponse\x12`\n" +
	"\x15GetHelmReleaseHistory\x12\".helm.GetHelmReleaseHistoryRequest\x1a#.helm.GetHelmReleaseHistoryResponse\x12D\n" +
	"\x13RollbackHelmRelease\x12 .helm.RollbackHelmReleaseRequest\x1a\v.helm.Empty\x12:\n" +
	"\x0fGetCapabilities\x12\v.helm.Empty\x1a\x1a.helm.CapabilitiesResponse\x12@\n" +
	"\x11SetClusterContext\x12\x1e.helm.SetClusterContextRequest\x1a\v.helm.EmptyB;Z9github.com/gknguyen/litelens/plugins/helm/go/internal/pb;b\x06proto3"

var (
	file_proto_helm_proto_rawDescOnce sync.Once
	file_proto_helm_proto_rawDescData []byte
)

func file_proto_helm_proto_rawDescGZIP() []byte {
	file_proto_helm_proto_rawDescOnce.Do(func() {
		file_proto_helm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_helm_proto_rawDesc), len(file_proto_helm_proto_rawDesc)))
	})
	return file_proto_helm_proto_rawDescData
}

var file_proto_helm_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_helm_proto_goTypes = []any{
	(*Empty)(nil),                         // 0: helm.Empty
	(*HelmChart)(nil),                     // 1: helm.HelmChart
	(*HelmChartDetail)(nil),               // 2: helm.HelmChartDetail
	(*HelmRepository)(nil),                // 3: helm.HelmRepository
	(*HelmRelease)(nil),                   // 4: helm.HelmRelease
	(*HelmReleaseResource)(nil),           // 5: helm.HelmReleaseResource
	(*HelmReleaseDetail)(nil),             // 6: helm.HelmReleaseDetail
	(*HelmReleaseRevisionHistory)(nil),    // 7: helm.HelmReleaseRevisionHistory
	(*ListHelmReleasesRequest)(nil),       // 8: helm.ListHelmReleasesRequest
	(*ListHelmReleasesResponse)(nil),      // 9: helm.ListHelmReleasesResponse
	(*ListHelmChartsResponse)(nil),        // 10: helm.ListHelmChartsResponse
	(*ListHelmRepositoriesResponse)(nil),  // 11: helm.ListHelmRepositoriesResponse
	(*ListHelmChartVersionsRequest)(nil),  // 12: helm.ListHelmChartVersionsRequest
	(*ListHelmChartVersionsResponse)(nil), // 13: helm.ListHelmChartVersionsResponse
	(*GetHelmChartDetailRequest)(nil),     // 14: helm.GetHelmChartDetailRequest
	(*GetArtifactHubReadmeRequest)(nil),   // 15: helm.GetArtifactHubReadmeRequest
	(*GetArtifactHubReadmeResponse)(nil),  // 16: helm.GetArtifactHubReadmeResponse
	(*InstallHelmChartRequest)(nil),       // 17: helm.InstallHelmChartRequest
	(*UpgradeHelmReleaseRequest)(nil),     // 18: helm.UpgradeHelmReleaseRequest
	(*DeleteHelmReleaseRequest)(nil),      // 19: helm.DeleteHelmReleaseRequest
	(*GetHelmReleaseByNameRequest)(nil),   // 20: helm.GetHelmReleaseByNameRequest
	(*GetHelmChartValuesRequest)(nil),     // 21: helm.GetHelmChartValuesRequest
	(*GetHelmChartValuesResponse)(nil),    // 22: helm.GetHelmChartValuesResponse
	(*GetHelmReleaseHistoryRequest)(nil),  // 23: helm.GetHelmReleaseHistoryRequest
	(*GetHelmReleaseHistoryResponse)(nil), // 24: helm.GetHelmReleaseHistoryResponse
	(*RollbackHelmReleaseRequest)(nil),    // 25: helm.RollbackHelmReleaseRequest
	(*CapabilitiesResponse)(nil),          // 26: helm.CapabilitiesResponse
	(*SetClusterContextRequest)(nil),      // 27: helm.SetClusterContextRequest
}
var file_proto_helm_proto_depIdxs = []int32{
	5,  // 0: helm.HelmReleaseDetail.resources:type_name -> helm.HelmReleaseResource
	4,  // 1: helm.ListHelmReleasesResponse.releases:type_name -> helm.HelmRelease
	1,  // 2: helm.ListHelmChartsResponse.charts:type_name -> helm.HelmChart
	3,  // 3: helm.ListHelmRepositoriesResponse.repositories:type_name -> helm.HelmRepository
	7,  // 4: helm.GetHelmReleaseHistoryResponse.history:type_name -> helm.HelmReleaseRevisionHistory
	0,  // 5: helm.Helm.ListHelmCharts:input_type -> helm.Empty
	0,  // 6: helm.Helm.ListHelmRepositories:input_type -> helm.Empty
	8,  // 7: helm.Helm.ListHelmReleases:input_type -> helm.ListHelmReleasesRequest
	12, // 8: helm.Helm.ListHelmChartVersions:input_type -> helm.ListHelmChartVersionsRequest
	14, // 9: helm.Helm.GetHelmChartDetail:input_type -> helm.GetHelmChartDetailRequest
	15, // 10: helm.Helm.GetArtifactHubReadme:input_type -> helm.GetArtifactHubReadmeRequest
	17, // 11: helm.Helm.InstallHelmChart:input_type -> helm.InstallHelmChartRequest
	18, // 12: helm.Helm.UpgradeHelmRelease:input_type -> helm.UpgradeHelmReleaseRequest
	19, // 13: helm.Helm.DeleteHelmRelease:input_type -> helm.DeleteHelmReleaseRequest
	19, // 14: helm.Helm.DeleteHelmReleaseWithCleanup:input_type -> helm.DeleteHelmReleaseRequest
	20, // 15: helm.Helm.GetHelmReleaseByName:input_type -> helm.GetHelmReleaseByNameRequest
	21, // 16: helm.Helm.GetHelmChartValues:input_type -> helm.GetHelmChartValuesRequest
	23, // 17: helm.Helm.GetHelmReleaseHistory:input_type -> helm.GetHelmReleaseHistoryRequest
	25, // 18: helm.Helm.RollbackHelmRelease:input_type -> helm.RollbackHelmReleaseRequest
	0,  // 19: helm.Helm.GetCapabilities:input_type -> helm.Empty
	27, // 20: helm.Helm.SetClusterContext:input_type -> helm.SetClusterContextRequest
	10, // 21: helm.Helm.ListHelmCharts:output_type -> helm.ListHelmChartsResponse
	11, // 22: helm.Helm.ListHelmRepositories:output_type -> helm.ListHelmRepositoriesResponse
	9,  // 23: helm.Helm.ListHelmReleases:output_type -> helm.ListHelmReleasesResponse
	13, // 24: helm.Helm.ListHelmChartVersions:output_type -> helm.ListHelmChartVersionsResponse
	2,  // 25: helm.Helm.GetHelmChartDetail:output_type -> helm.HelmChartDetail
	16, // 26: helm.Helm.GetArtifactHubReadme:output_type -> helm.GetArtifactHubReadmeResponse
	0,  // 27: helm.Helm.InstallHelmChart:output_type -> helm.Empty
	0,  // 28: helm.Helm.UpgradeHelmRelease:output_type -> helm.Empty
	0,  // 29: helm.Helm.DeleteHelmRelease:output_type -> helm.Empty
	0,  // 30: helm.Helm.DeleteHelmReleaseWithCleanup:output_type -> helm.Empty
	6,  // 31: helm.Helm.GetHelmReleaseByName:output_type -> helm.HelmReleaseDetail
	22, // 32: helm.Helm.GetHelmChartValues:output_type -> helm.GetHelmChartValuesResponse
	24, // 33: helm.Helm.GetHelmReleaseHistory:output_type -> helm.GetHelmReleaseHistoryResponse
	0,  // 34: helm.Helm.RollbackHelmRelease:output_type -> helm.Empty
	26, // 35: helm.Helm.GetCapabilities:output_type -> helm.CapabilitiesResponse
	0,  // 36: helm.Helm.SetClusterContext:output_type -> helm.Empty
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_helm_proto_init() }
func file_proto_helm_proto_init() {
	if File_proto_helm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_helm_proto_rawDesc), len(file_proto_helm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_helm_proto_goTypes,
		DependencyIndexes: file_proto_helm_proto_depIdxs,
		MessageInfos:      file_proto_helm_proto_msgTypes,
	}.Build()
	File_proto_helm_proto = out.File
	file_proto_helm_proto_goTypes = nil
	file_proto_helm_proto_depIdxs = nil
}
