// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: proto/helm.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Helm_ListHelmCharts_FullMethodName               = "/helm.Helm/ListHelmCharts"
	Helm_ListHelmRepositories_FullMethodName         = "/helm.Helm/ListHelmRepositories"
	Helm_ListHelmReleases_FullMethodName             = "/helm.Helm/ListHelmReleases"
	Helm_ListHelmChartVersions_FullMethodName        = "/helm.Helm/ListHelmChartVersions"
	Helm_GetHelmChartDetail_FullMethodName           = "/helm.Helm/GetHelmChartDetail"
	Helm_GetArtifactHubReadme_FullMethodName         = "/helm.Helm/GetArtifactHubReadme"
	Helm_InstallHelmChart_FullMethodName             = "/helm.Helm/InstallHelmChart"
	Helm_UpgradeHelmRelease_FullMethodName           = "/helm.Helm/UpgradeHelmRelease"
	Helm_DeleteHelmRelease_FullMethodName            = "/helm.Helm/DeleteHelmRelease"
	Helm_DeleteHelmReleaseWithCleanup_FullMethodName = "/helm.Helm/DeleteHelmReleaseWithCleanup"
	Helm_GetHelmReleaseByName_FullMethodName         = "/helm.Helm/GetHelmReleaseByName"
	Helm_GetHelmChartValues_FullMethodName           = "/helm.Helm/GetHelmChartValues"
	Helm_GetHelmReleaseHistory_FullMethodName        = "/helm.Helm/GetHelmReleaseHistory"
	Helm_RollbackHelmRelease_FullMethodName          = "/helm.Helm/RollbackHelmRelease"
	Helm_GetCapabilities_FullMethodName              = "/helm.Helm/GetCapabilities"
	Helm_SetClusterContext_FullMethodName            = "/helm.Helm/SetClusterContext"
)

// HelmClient is the client API for Helm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelmClient interface {
	ListHelmCharts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListHelmChartsResponse, error)
	ListHelmRepositories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListHelmRepositoriesResponse, error)
	ListHelmReleases(ctx context.Context, in *ListHelmReleasesRequest, opts ...grpc.CallOption) (*ListHelmReleasesResponse, error)
	ListHelmChartVersions(ctx context.Context, in *ListHelmChartVersionsRequest, opts ...grpc.CallOption) (*ListHelmChartVersionsResponse, error)
	GetHelmChartDetail(ctx context.Context, in *GetHelmChartDetailRequest, opts ...grpc.CallOption) (*HelmChartDetail, error)
	GetArtifactHubReadme(ctx context.Context, in *GetArtifactHubReadmeRequest, opts ...grpc.CallOption) (*GetArtifactHubReadmeResponse, error)
	InstallHelmChart(ctx context.Context, in *InstallHelmChartRequest, opts ...grpc.CallOption) (*Empty, error)
	UpgradeHelmRelease(ctx context.Context, in *UpgradeHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteHelmRelease(ctx context.Context, in *DeleteHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteHelmReleaseWithCleanup(ctx context.Context, in *DeleteHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error)
	GetHelmReleaseByName(ctx context.Context, in *GetHelmReleaseByNameRequest, opts ...grpc.CallOption) (*HelmReleaseDetail, error)
	GetHelmChartValues(ctx context.Context, in *GetHelmChartValuesRequest, opts ...grpc.CallOption) (*GetHelmChartValuesResponse, error)
	GetHelmReleaseHistory(ctx context.Context, in *GetHelmReleaseHistoryRequest, opts ...grpc.CallOption) (*GetHelmReleaseHistoryResponse, error)
	RollbackHelmRelease(ctx context.Context, in *RollbackHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error)
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	SetClusterContext(ctx context.Context, in *SetClusterContextRequest, opts ...grpc.CallOption) (*Empty, error)
}

type helmClient struct {
	cc grpc.ClientConnInterface
}

func NewHelmClient(cc grpc.ClientConnInterface) HelmClient {
	return &helmClient{cc}
}

func (c *helmClient) ListHelmCharts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListHelmChartsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHelmChartsResponse)
	err := c.cc.Invoke(ctx, Helm_ListHelmCharts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) ListHelmRepositories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListHelmRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHelmRepositoriesResponse)
	err := c.cc.Invoke(ctx, Helm_ListHelmRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) ListHelmReleases(ctx context.Context, in *ListHelmReleasesRequest, opts ...grpc.CallOption) (*ListHelmReleasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHelmReleasesResponse)
	err := c.cc.Invoke(ctx, Helm_ListHelmReleases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) ListHelmChartVersions(ctx context.Context, in *ListHelmChartVersionsRequest, opts ...grpc.CallOption) (*ListHelmChartVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHelmChartVersionsResponse)
	err := c.cc.Invoke(ctx, Helm_ListHelmChartVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) GetHelmChartDetail(ctx context.Context, in *GetHelmChartDetailRequest, opts ...grpc.CallOption) (*HelmChartDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelmChartDetail)
	err := c.cc.Invoke(ctx, Helm_GetHelmChartDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) GetArtifactHubReadme(ctx context.Context, in *GetArtifactHubReadmeRequest, opts ...grpc.CallOption) (*GetArtifactHubReadmeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtifactHubReadmeResponse)
	err := c.cc.Invoke(ctx, Helm_GetArtifactHubReadme_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) InstallHelmChart(ctx context.Context, in *InstallHelmChartRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Helm_InstallHelmChart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) UpgradeHelmRelease(ctx context.Context, in *UpgradeHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Helm_UpgradeHelmRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) DeleteHelmRelease(ctx context.Context, in *DeleteHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Helm_DeleteHelmRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) DeleteHelmReleaseWithCleanup(ctx context.Context, in *DeleteHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Helm_DeleteHelmReleaseWithCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) GetHelmReleaseByName(ctx context.Context, in *GetHelmReleaseByNameRequest, opts ...grpc.CallOption) (*HelmReleaseDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelmReleaseDetail)
	err := c.cc.Invoke(ctx, Helm_GetHelmReleaseByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) GetHelmChartValues(ctx context.Context, in *GetHelmChartValuesRequest, opts ...grpc.CallOption) (*GetHelmChartValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHelmChartValuesResponse)
	err := c.cc.Invoke(ctx, Helm_GetHelmChartValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) GetHelmReleaseHistory(ctx context.Context, in *GetHelmReleaseHistoryRequest, opts ...grpc.CallOption) (*GetHelmReleaseHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHelmReleaseHistoryResponse)
	err := c.cc.Invoke(ctx, Helm_GetHelmReleaseHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) RollbackHelmRelease(ctx context.Context, in *RollbackHelmReleaseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Helm_RollbackHelmRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, Helm_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helmClient) SetClusterContext(ctx context.Context, in *SetClusterContextRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Helm_SetClusterContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelmServer is the server API for Helm service.
// All implementations must embed UnimplementedHelmServer
// for forward compatibility.
type HelmServer interface {
	ListHelmCharts(context.Context, *Empty) (*ListHelmChartsResponse, error)
	ListHelmRepositories(context.Context, *Empty) (*ListHelmRepositoriesResponse, error)
	ListHelmReleases(context.Context, *ListHelmReleasesRequest) (*ListHelmReleasesResponse, error)
	ListHelmChartVersions(context.Context, *ListHelmChartVersionsRequest) (*ListHelmChartVersionsResponse, error)
	GetHelmChartDetail(context.Context, *GetHelmChartDetailRequest) (*HelmChartDetail, error)
	GetArtifactHubReadme(context.Context, *GetArtifactHubReadmeRequest) (*GetArtifactHubReadmeResponse, error)
	InstallHelmChart(context.Context, *InstallHelmChartRequest) (*Empty, error)
	UpgradeHelmRelease(context.Context, *UpgradeHelmReleaseRequest) (*Empty, error)
	DeleteHelmRelease(context.Context, *DeleteHelmReleaseRequest) (*Empty, error)
	DeleteHelmReleaseWithCleanup(context.Context, *DeleteHelmReleaseRequest) (*Empty, error)
	GetHelmReleaseByName(context.Context, *GetHelmReleaseByNameRequest) (*HelmReleaseDetail, error)
	GetHelmChartValues(context.Context, *GetHelmChartValuesRequest) (*GetHelmChartValuesResponse, error)
	GetHelmReleaseHistory(context.Context, *GetHelmReleaseHistoryRequest) (*GetHelmReleaseHistoryResponse, error)
	RollbackHelmRelease(context.Context, *RollbackHelmReleaseRequest) (*Empty, error)
	GetCapabilities(context.Context, *Empty) (*CapabilitiesResponse, error)
	SetClusterContext(context.Context, *SetClusterContextRequest) (*Empty, error)
	mustEmbedUnimplementedHelmServer()
}

// UnimplementedHelmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelmServer struct{}

func (UnimplementedHelmServer) ListHelmCharts(context.Context, *Empty) (*ListHelmChartsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHelmCharts not implemented")
}
func (UnimplementedHelmServer) ListHelmRepositories(context.Context, *Empty) (*ListHelmRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHelmRepositories not implemented")
}
func (UnimplementedHelmServer) ListHelmReleases(context.Context, *ListHelmReleasesRequest) (*ListHelmReleasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHelmReleases not implemented")
}
func (UnimplementedHelmServer) ListHelmChartVersions(context.Context, *ListHelmChartVersionsRequest) (*ListHelmChartVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHelmChartVersions not implemented")
}
func (UnimplementedHelmServer) GetHelmChartDetail(context.Context, *GetHelmChartDetailRequest) (*HelmChartDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHelmChartDetail not implemented")
}
func (UnimplementedHelmServer) GetArtifactHubReadme(context.Context, *GetArtifactHubReadmeRequest) (*GetArtifactHubReadmeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtifactHubReadme not implemented")
}
func (UnimplementedHelmServer) InstallHelmChart(context.Context, *InstallHelmChartRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallHelmChart not implemented")
}
func (UnimplementedHelmServer) UpgradeHelmRelease(context.Context, *UpgradeHelmReleaseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeHelmRelease not implemented")
}
func (UnimplementedHelmServer) DeleteHelmRelease(context.Context, *DeleteHelmReleaseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHelmRelease not implemented")
}
func (UnimplementedHelmServer) DeleteHelmReleaseWithCleanup(context.Context, *DeleteHelmReleaseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHelmReleaseWithCleanup not implemented")
}
func (UnimplementedHelmServer) GetHelmReleaseByName(context.Context, *GetHelmReleaseByNameRequest) (*HelmReleaseDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHelmReleaseByName not implemented")
}
func (UnimplementedHelmServer) GetHelmChartValues(context.Context, *GetHelmChartValuesRequest) (*GetHelmChartValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHelmChartValues not implemented")
}
func (UnimplementedHelmServer) GetHelmReleaseHistory(context.Context, *GetHelmReleaseHistoryRequest) (*GetHelmReleaseHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHelmReleaseHistory not implemented")
}
func (UnimplementedHelmServer) RollbackHelmRelease(context.Context, *RollbackHelmReleaseRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackHelmRelease not implemented")
}
func (UnimplementedHelmServer) GetCapabilities(context.Context, *Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedHelmServer) SetClusterContext(context.Context, *SetClusterContextRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetClusterContext not implemented")
}
func (UnimplementedHelmServer) mustEmbedUnimplementedHelmServer() {}
func (UnimplementedHelmServer) testEmbeddedByValue()              {}

// UnsafeHelmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelmServer will
// result in compilation errors.
type UnsafeHelmServer interface {
	mustEmbedUnimplementedHelmServer()
}

func RegisterHelmServer(s grpc.ServiceRegistrar, srv HelmServer) {
	// If the following call panics, it indicates UnimplementedHelmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Helm_ServiceDesc, srv)
}

func _Helm_ListHelmCharts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).ListHelmCharts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_ListHelmCharts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).ListHelmCharts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_ListHelmRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).ListHelmRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_ListHelmRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).ListHelmRepositories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_ListHelmReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHelmReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).ListHelmReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_ListHelmReleases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).ListHelmReleases(ctx, req.(*ListHelmReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_ListHelmChartVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHelmChartVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).ListHelmChartVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_ListHelmChartVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).ListHelmChartVersions(ctx, req.(*ListHelmChartVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_GetHelmChartDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelmChartDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).GetHelmChartDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_GetHelmChartDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).GetHelmChartDetail(ctx, req.(*GetHelmChartDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_GetArtifactHubReadme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactHubReadmeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).GetArtifactHubReadme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_GetArtifactHubReadme_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).GetArtifactHubReadme(ctx, req.(*GetArtifactHubReadmeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_InstallHelmChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallHelmChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).InstallHelmChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_InstallHelmChart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).InstallHelmChart(ctx, req.(*InstallHelmChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_UpgradeHelmRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeHelmReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).UpgradeHelmRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_UpgradeHelmRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).UpgradeHelmRelease(ctx, req.(*UpgradeHelmReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_DeleteHelmRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHelmReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).DeleteHelmRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_DeleteHelmRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).DeleteHelmRelease(ctx, req.(*DeleteHelmReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_DeleteHelmReleaseWithCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHelmReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).DeleteHelmReleaseWithCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_DeleteHelmReleaseWithCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).DeleteHelmReleaseWithCleanup(ctx, req.(*DeleteHelmReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_GetHelmReleaseByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelmReleaseByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).GetHelmReleaseByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_GetHelmReleaseByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).GetHelmReleaseByName(ctx, req.(*GetHelmReleaseByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_GetHelmChartValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelmChartValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).GetHelmChartValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_GetHelmChartValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).GetHelmChartValues(ctx, req.(*GetHelmChartValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_GetHelmReleaseHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelmReleaseHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).GetHelmReleaseHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_GetHelmReleaseHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).GetHelmReleaseHistory(ctx, req.(*GetHelmReleaseHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_RollbackHelmRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackHelmReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).RollbackHelmRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_RollbackHelmRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).RollbackHelmRelease(ctx, req.(*RollbackHelmReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helm_SetClusterContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClusterContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelmServer).SetClusterContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helm_SetClusterContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelmServer).SetClusterContext(ctx, req.(*SetClusterContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Helm_ServiceDesc is the grpc.ServiceDesc for Helm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helm.Helm",
	HandlerType: (*HelmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHelmCharts",
			Handler:    _Helm_ListHelmCharts_Handler,
		},
		{
			MethodName: "ListHelmRepositories",
			Handler:    _Helm_ListHelmRepositories_Handler,
		},
		{
			MethodName: "ListHelmReleases",
			Handler:    _Helm_ListHelmReleases_Handler,
		},
		{
			MethodName: "ListHelmChartVersions",
			Handler:    _Helm_ListHelmChartVersions_Handler,
		},
		{
			MethodName: "GetHelmChartDetail",
			Handler:    _Helm_GetHelmChartDetail_Handler,
		},
		{
			MethodName: "GetArtifactHubReadme",
			Handler:    _Helm_GetArtifactHubReadme_Handler,
		},
		{
			MethodName: "InstallHelmChart",
			Handler:    _Helm_InstallHelmChart_Handler,
		},
		{
			MethodName: "UpgradeHelmRelease",
			Handler:    _Helm_UpgradeHelmRelease_Handler,
		},
		{
			MethodName: "DeleteHelmRelease",
			Handler:    _Helm_DeleteHelmRelease_Handler,
		},
		{
			MethodName: "DeleteHelmReleaseWithCleanup",
			Handler:    _Helm_DeleteHelmReleaseWithCleanup_Handler,
		},
		{
			MethodName: "GetHelmReleaseByName",
			Handler:    _Helm_GetHelmReleaseByName_Handler,
		},
		{
			MethodName: "GetHelmChartValues",
			Handler:    _Helm_GetHelmChartValues_Handler,
		},
		{
			MethodName: "GetHelmReleaseHistory",
			Handler:    _Helm_GetHelmReleaseHistory_Handler,
		},
		{
			MethodName: "RollbackHelmRelease",
			Handler:    _Helm_RollbackHelmRelease_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _Helm_GetCapabilities_Handler,
		},
		{
			MethodName: "SetClusterContext",
			Handler:    _Helm_SetClusterContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/helm.proto",
}
